// ============================================================================
// File: Models/MqttPayload.cs
// Purpose: Wire-format model representing a single message to be published
//          to the MQTT broker. This is the unit of work flowing through
//          the Channel<T> pipeline from pollers to the MQTT publisher.
//
// DATA FLOW:
//   MachinePollerService creates MqttPayload:
//     1. Serializes CncMachineData → JSON bytes (PayloadBytes)
//     2. Constructs the MQTT topic string
//     3. Sets QoS and Retain flags
//     4. Writes the MqttPayload to the Channel<MqttPayload>
//
//   MqttPublisherService consumes MqttPayload:
//     1. Reads batch of payloads from the channel
//     2. Creates MqttApplicationMessage for each payload
//     3. Publishes to the broker
//
// DESIGN DECISION — PRE-SERIALIZED BYTES:
//   PayloadBytes stores pre-serialized JSON (byte[]) rather than the
//   CncMachineData object. This means serialization happens on the poller
//   thread, distributing the CPU cost across many threads rather than
//   concentrating it on the single publisher thread. This improves throughput
//   when publishing hundreds of messages per second.
// ============================================================================

namespace ElpisEdgeConnect.Models;

/// <summary>
/// Wire-format payload published to MQTT.
/// Optimized for downstream consumers (SCADA, dashboards, historians).
/// 
/// This model is intentionally slim — it carries pre-serialized bytes
/// and routing metadata, nothing more. The heavy CncMachineData object
/// is serialized once and discarded, reducing GC pressure.
/// </summary>
public sealed class MqttPayload
{
    /// <summary>
    /// MQTT topic this payload should be published to.
    /// 
    /// Format: "{TopicPrefix}/{machineId}/data"
    /// Example: "factory/cnc/CNC-001/data"
    /// 
    /// Special topics for bridge status:
    ///   "{TopicPrefix}/$bridge/status"       → "online"/"offline"
    ///   "{TopicPrefix}/$bridge/diagnostics"   → JSON health metrics
    /// 
    /// The '$' prefix convention helps subscribers distinguish between
    /// machine data topics and bridge management topics.
    /// </summary>
    public required string Topic { get; init; }

    /// <summary>
    /// Pre-serialized JSON payload as UTF-8 bytes.
    /// 
    /// WHY BYTES INSTEAD OF STRING:
    ///   - MQTTnet's PublishAsync accepts byte[] directly — no string→bytes conversion
    ///   - Avoids double-encoding (string allocation + UTF-8 encoding at publish time)
    ///   - Serialization is done on the poller thread (parallelized) rather than
    ///     the single publisher thread (bottleneck)
    ///   - Reduces memory allocations and GC pressure in high-throughput scenarios
    /// 
    /// Generated by: JsonSerializer.SerializeToUtf8Bytes(cncMachineData)
    /// </summary>
    public required byte[] PayloadBytes { get; init; }

    /// <summary>
    /// Quality of Service level for this specific message.
    /// 
    /// Can override the global QoS setting per message:
    ///   0 = AtMostOnce  (fire-and-forget, fastest)
    ///   1 = AtLeastOnce (guaranteed delivery, may duplicate) — DEFAULT
    ///   2 = ExactlyOnce (guaranteed once, slowest)
    /// 
    /// Example: You might use QoS 0 for position data (high frequency,
    /// lost data is quickly replaced) but QoS 1 for alarm events.
    /// </summary>
    public int QoS { get; init; } = 1;

    /// <summary>
    /// Whether the MQTT broker should retain this message.
    /// 
    /// When true, the broker stores the last message for this topic.
    /// New subscribers immediately receive the retained message when they
    /// subscribe — they don't have to wait for the next publish.
    /// 
    /// USE CASES:
    ///   - true:  Bridge status ("online"/"offline"), diagnostics
    ///   - false: Machine telemetry data (default — don't retain old readings)
    /// 
    /// WARNING: Retaining high-frequency data wastes broker storage.
    /// Only retain "current state" topics that new subscribers need immediately.
    /// </summary>
    public bool Retain { get; init; } = false;

    /// <summary>
    /// UTC timestamp when this payload was created.
    /// 
    /// Used for:
    ///   - Ordering messages in the channel (newest first if dropping)
    ///   - Detecting stale messages (if MQTT publishing is delayed)
    ///   - Logging/diagnostics (correlating publish time with collection time)
    /// 
    /// Note: This is when the payload was CREATED, which is slightly after
    /// the CncMachineData.Timestamp (data collection time). The difference
    /// is the serialization overhead (typically <1ms).
    /// </summary>
    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Source machine ID for logging and diagnostics.
    /// 
    /// Not included in the MQTT message itself (it's already in the JSON payload
    /// and the topic). Used only for logging when publish succeeds/fails:
    ///   "Failed to publish to factory/cnc/CNC-001/data for CNC-001"
    /// </summary>
    public required string MachineId { get; init; }
}
