// ============================================================================
// File: Configuration/DraftId.cs
// Purpose: Strongly-typed identifier for a configuration draft.
// Reference: PHASE1_EXECUTION_PLAN.md Milestone B2
// ============================================================================

using System;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ElpisEdgeConnect.Core.Configuration;

/// <summary>
/// Opaque identifier for a configuration draft. Generated by
/// <c>IConfigurationManager.CreateDraftAsync</c> and used as the key into
/// the drafts directory and the parameter to validate / apply / discard
/// methods. Format is intentionally opaque so future revisions can change
/// the encoding without breaking callers.
/// </summary>
/// <remarks>
/// <para>
/// Current encoding: <c>draft-{utc-timestamp}-{6-char random suffix}</c>,
/// e.g. <c>draft-20260408T143022Z-a4f1b2</c>. The timestamp prefix makes
/// drafts naturally chronological when listed.
/// </para>
/// <para>
/// JSON-serializes as a plain string (e.g., <c>"draft-..."</c>) via
/// <see cref="DraftIdJsonConverter"/>, not as an object with named
/// properties. This keeps audit log lines compact and round-trip cleanly.
/// </para>
/// </remarks>
[JsonConverter(typeof(DraftIdJsonConverter))]
public readonly record struct DraftId
{
    private readonly string _value;

    /// <summary>Construct a draft id from an existing string value (e.g., when reading from disk).</summary>
    public DraftId(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("Draft id cannot be null, empty, or whitespace.", nameof(value));
        }
        _value = value;
    }

    /// <summary>The string representation of the draft id.</summary>
    public string Value => _value ?? string.Empty;

    /// <summary>True if this is the default (uninitialized) draft id.</summary>
    public bool IsEmpty => string.IsNullOrEmpty(_value);

    /// <summary>
    /// Generate a fresh draft id using the current UTC time. Includes a
    /// short random suffix to disambiguate drafts created within the same
    /// second.
    /// </summary>
    public static DraftId NewId()
    {
        var timestamp = DateTime.UtcNow.ToString("yyyyMMddTHHmmssZ", CultureInfo.InvariantCulture);
        var suffix = Convert.ToHexString(Guid.NewGuid().ToByteArray()).Substring(0, 6).ToLowerInvariant();
        return new DraftId($"draft-{timestamp}-{suffix}");
    }

    /// <inheritdoc/>
    public override string ToString() => Value;
}

/// <summary>
/// JSON converter that serializes <see cref="DraftId"/> as a plain string.
/// </summary>
public sealed class DraftIdJsonConverter : JsonConverter<DraftId>
{
    /// <inheritdoc/>
    public override DraftId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
        {
            return default;
        }
        var value = reader.GetString();
        return string.IsNullOrEmpty(value) ? default : new DraftId(value);
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, DraftId value, JsonSerializerOptions options)
    {
        if (value.IsEmpty)
        {
            writer.WriteNullValue();
        }
        else
        {
            writer.WriteStringValue(value.Value);
        }
    }
}
